### PR TITLE
Fix study rooms

### LINKED ISSUE #1256: Changed Studyrooms API causes SQL exception
```
2019-02-04 21:04:04.294 29240-29370/de.tum.in.tumcampus W/System.err: android.database.sqlite.SQLiteConstraintException: NOT NULL constraint failed: study_rooms.code (code 1299 SQLITE_CONSTRAINT_NOTNULL)
2019-02-04 21:04:04.294 29240-29370/de.tum.in.tumcampus W/System.err:     at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
2019-02-04 21:04:04.294 29240-29370/de.tum.in.tumcampus W/System.err:     at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:796)
2019-02-04 21:04:04.294 29240-29370/de.tum.in.tumcampus W/System.err:     at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
2019-02-04 21:04:04.294 29240-29370/de.tum.in.tumcampus W/System.err:     at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
2019-02-04 21:04:04.294 29240-29370/de.tum.in.tumcampus W/System.err:     at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeInsert(FrameworkSQLiteStatement.java:51)
2019-02-04 21:04:04.294 29240-29370/de.tum.in.tumcampus W/System.err:     at androidx.room.EntityInsertionAdapter.insert(EntityInsertionAdapter.java:80)
2019-02-04 21:04:04.294 29240-29370/de.tum.in.tumcampus W/System.err:     at de.tum.in.tumcampusapp.component.ui.studyroom.StudyRoomDao_Impl.insert(StudyRoomDao_Impl.java:85)
2019-02-04 21:04:04.294 29240-29370/de.tum.in.tumcampus W/System.err:     at de.tum.in.tumcampusapp.component.ui.studyroom.StudyRoomGroupManager$updateDatabase$1.invoke(StudyRoomGroupManager.kt:31)
2019-02-04 21:04:04.294 29240-29370/de.tum.in.tumcampus W/System.err:     at de.tum.in.tumcampusapp.component.ui.studyroom.StudyRoomGroupManager$updateDatabase$1.invoke(StudyRoomGroupManager.kt:12)
2019-02-04 21:04:04.294 29240-29370/de.tum.in.tumcampus W/System.err:     at org.jetbrains.anko.AsyncKt$doAsync$1.invoke(Async.kt:143)
2019-02-04 21:04:04.294 29240-29370/de.tum.in.tumcampus W/System.err:     at org.jetbrains.anko.AsyncKt$doAsync$1.invoke(Unknown Source:0)
2019-02-04 21:04:04.294 29240-29370/de.tum.in.tumcampus W/System.err:     at org.jetbrains.anko.AsyncKt$sam$java_util_concurrent_Callable$0.call(Unknown Source:2)
2019-02-04 21:04:04.294 29240-29370/de.tum.in.tumcampus W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2019-02-04 21:04:04.294 29240-29370/de.tum.in.tumcampus W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
2019-02-04 21:04:04.294 29240-29370/de.tum.in.tumcampus W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2019-02-04 21:04:04.294 29240-29370/de.tum.in.tumcampus W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2019-02-04 21:04:04.294 29240-29370/de.tum.in.tumcampus W/System.err:     at java.lang.Thread.run(Thread.java:764)
2019-02-04 21:04:04.306 29240-29295/de.tum.in.tumcampus E/libc: Access denied finding property "vendor.debug.egl.swapinterval"
2019-02-04 21:04:04.357 29240-29295/de.tum.in.tumcampus I/chatty: uid=10283(de.tum.in.tumcampus) RenderThread identical 3 lines
2019-02-04 21:04:04.375 29240-29295/de.tum.in.tumcampus E/libc: Access denied finding property "vendor.debug.egl.swapinterval"
2019-02-04 21:04:04.391 29240-29295/de.tum.in.tumcampus E/libc: Access denied finding property "vendor.debug.egl.swapinterval"
2019-02-04 21:04:04.443 29240-29295/de.tum.in.tumcampus I/chatty: uid=10283(de.tum.in.tumcampus) RenderThread identical 3 lines
2019-02-04 21:04:04.464 29240-29295/de.tum.in.tumcampus E/libc: Access denied finding property "vendor.debug.egl.swapinterval"
```

Screen stays blank and no information is displayed.

### PR DESCRIPTION
**Pull request by jacqueline8711**
## Issue
Fixes  #1256

- Fixes SQL exception being thrown by not inserting incomplete rooms
- Keeps showing the locations that don't have rooms yet (website shows them too)
- Adds placeholder for locations without rooms

## Screenshot
screenshot_20190207-114010

## Why this is useful for all students
Study rooms are being shown again and the students know that there will be new rooms for new locations in the future

### CODE REVIEW

File: app/src/main/java/de/tum/in/tumcampusapp/component/ui/studyroom/StudyRoomGroupManager.kt [hunk 1]
```diff
@@ -28,7 +28,15 @@ class StudyRoomGroupManager(context: Context) {
             groupsDao.insert(*groups.toTypedArray())
 
             groups.forEach { group ->
-                roomsDao.insert(*group.rooms.toTypedArray())
+                group.rooms.forEach { room ->
+                    // only insert rooms that have data
+                    if (room.code != ""
```
Comment (kordianbruck) [inline app/src/main/java/de/tum/in/tumcampusapp/component/ui/studyroom/StudyRoomGroupManager.kt]: you could use the `isBlank` or `isEmpty` functions. While this might work, it is not technically correct, as you must compare `strings` with .equal to check for value equality. (Now you are checking reference equality, which works, cause Java has a central String pool)
